version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: pg-container
    image: postgres:latest
    ports:
      - "${POSTGRES_BIND_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE_NAME}
      - PGDATA=${POSTGRES_DATA}
    volumes:
      - ./.docker/postgres/data:${POSTGRES_DATA}:rw
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

###< doctrine/doctrine-bundle ###
