#index:
#    path: /
#    controller: App\Controller\DefaultController::index
post_read:
  path: /api/v1/posts
  controller: App\Controller\PostController::index
  methods: [GET]

post_create:
  path: /api/v1/posts
  controller: App\Controller\PostController::create
  methods: [POST]
