#index:
#    path: /
#    controller: App\Controller\DefaultController::index
post_read:
  path: /api/v1/posts
  controller: App\Controller\PostController::index
  methods: [GET]

post_create:
  path: /api/v1/posts
  controller: App\Controller\PostController::create
  methods: [POST]

post_delete:
  path: /api/v1/posts/{postId}
  controller: App\Controller\PostController::delete
  methods: [DELETE]
  requirements:
    postId: '\d+'

post_update:
  path: /api/v1/posts/{postId}
  controller: App\Controller\PostController::update
  methods: [PATCH]
  requirements:
    postId: '\d+'
